// Every on-screen string lives here, keyed by screen. Components never hold user-facing text.
// tests/unit/test_copy.py checks the limits and banned words from section 12.6 of the build prompt.

export const app = {
  name: "Research Workbench",
  principle:
    "The tool does the searching, sorting and maths and shows its working. You check what matters and make the call.",
  history: "History",
  help: "Help",
  settings: "Settings",
  back: "Back",
  details: "Details",
  close: "Close",
  phases: ["Frame", "Gather", "Conclude"],
  stepOf: (n: number) => `Step ${n} of 12`,
  next: (title: string) => `Next: ${title}`,
  done: "Done",
  locked: "Locked",
  sampleTag: "Sample data (simulated)",
  narrowNotice: "This screen is too narrow to work in. You can read the case here, but use a wider window to make changes.",
  loading: "Loading the case.",
  futureStep: (title: string) => `Finish "${title}" first.`,
  movingOn: (title: string) => `Done. Moving on to ${title.toLowerCase()}.`,
};

export const banners = {
  demo: "Demo data mode: stored responses, not live.",
  noKeys: "Live keys not found, so the app opened in demo data mode.",
  jobFailed: "This step didn't finish.",
  liveFailed: "The live AI or search service failed twice in a row. You can switch this case to its stored sample answers.",
  liveFailedBlank: "The live AI or search service failed twice in a row. Press Try again in a minute, or open a sample case to show the steps.",
  limitReached: (what: string) => `The ${what} is reached, so no more AI or search calls will be made. Open Settings to see the spend.`,
  limitNear: (what: string) => `This case is close to the ${what}. Open Settings to see the spend.`,
  limitNames: { calls: "AI call limit for this case", daily: "daily spending limit", search: "search limit for this case" } as Record<string, string>,
};

export const passcode = {
  title: "Enter the passcode",
  hint: "This workbench is private. Ask the person who set it up for the passcode.",
  label: "Passcode",
};

// Screen titles, the instruction under each title, and the primary button (section 12.4).
export const steps: Record<number, { title: string; instruction: string; primary: string }> = {
  1: {
    title: "Describe the ask",
    instruction:
      "Paste the client's request exactly as they wrote it. If they've already sent files, add them too, so we use what you have before asking for more.",
    primary: "Check the ask",
  },
  2: {
    title: "Confirm the question",
    instruction:
      "Check that this matches what the client wants answered. You can edit any box. Once you confirm, we'll draft the ideas to test.",
    primary: "Confirm question",
  },
  3: {
    title: "Set the targets",
    instruction:
      "Each idea has a target: the number that decides whether it holds up. Change anything that looks wrong. After you lock the targets, they can't be edited.",
    primary: "Lock targets",
  },
  4: {
    title: "Plan the research",
    instruction:
      "Check where each answer will come from and what would be sent out. No message goes to the client or experts from this tool. You send the requests yourself, then mark them as sent.",
    primary: "Mark as sent",
  },
  5: {
    title: "Gathering evidence",
    instruction:
      "We're collecting evidence from the sources you chose. This usually takes a minute or two. You can stop at any time and keep what we've found.",
    primary: "Stop collecting",
  },
  6: {
    title: "Checking the evidence",
    instruction: "We're merging duplicates and rating each source. You don't need to do anything here.",
    primary: "Review evidence",
  },
  7: {
    title: "Review the evidence",
    instruction:
      "Check what we found before you run the tests. Start with the items that need your call. Then open each source that passed our quality check and mark it as seen. The quick double-check is optional.",
    primary: "Run tests",
  },
  8: {
    title: "Results",
    instruction: "Here's how each idea compares with its target. Open a card to see the evidence behind it.",
    primary: "Fill the gaps",
  },
  9: {
    title: "Fill the gaps",
    instruction:
      "These ideas don't have enough evidence yet. Check the question we drafted, send it, mark it as sent, then add the reply here.",
    primary: "Add reply",
  },
  10: {
    title: "The answer",
    instruction:
      "This is what the evidence adds up to. Each statement links to its evidence. Check the sources before you rely on it.",
    primary: "Stress-test",
  },
  11: {
    title: "What if...",
    instruction: "Move a slider to see whether the answer would change. Your locked plan stays as it is.",
    primary: "Write conclusion",
  },
  12: {
    title: "Your conclusion",
    instruction:
      "Here's a one-page summary. Write your own conclusion in the box. We don't write it for you, and nothing is sent anywhere.",
    primary: "Save conclusion",
  },
};

// Every button label in the app. At most four words, starting with a verb.
export const buttons = {
  startCase: "Start a case",
  trySample: "Try a sample",
  importCase: "Import a case",
  open: "Open",
  delete: "Delete",
  continue: "Continue",
  tryAgain: "Try again",
  cancel: "Cancel",
  confirm: "Confirm",
  lockTargets: "Lock targets",
  markSent: "Mark as sent",
  runTests: "Run tests",
  resetCase: "Reset case",
  deleteCase: "Delete case",
  removeIdea: "Remove idea",
  restoreIdea: "Restore idea",
  addSource: "Add source",
  saveSource: "Save source",
  copy: "Copy",
  copied: "Copied",
  download: "Download",
  editSearch: "Edit search",
  saveSearch: "Save search",
  stopCollecting: "Stop collecting",
  addReply: "Add reply",
  addFile: "Add file",
  reviewEvidence: "Review evidence",
  openSource: "Open source",
  viewSource: "View source",
  sendToReview: "Move to my review",
  accept: "Accept",
  acceptMenu: "Accept",
  acceptClient: "Accept as client's data",
  useClaim: "Use as client's claim",
  useSenseCheck: "Use as sense check",
  reject: "Reject",
  acceptConfirmFormula: "Accept and confirm formula",
  skipCheck: "Skip",
  useAsTarget: "Use this as the new target",
  matches: "Matches",
  doesntMatch: "Doesn't match",
  saveLinks: "Save changes",
  fillGaps: "Fill the gaps",
  addItUp: "Add it up",
  draftQuestion: "Draft question",
  addAnotherIdea: "Add another idea",
  skipForNow: "Skip for now",
  testAgain: "Test again",
  useSampleReply: "Use the sample reply",
  markNotNeeded: "Mark as not needed",
  stressTest: "Stress-test",
  writeConclusion: "Write conclusion",
  reset: "Reset",
  saveConclusion: "Save conclusion",
  printPdf: "Print or save PDF",
  downloadMarkdown: "Download Markdown",
  downloadJson: "Download JSON",
  exportCsv: "Export CSV",
  skipToStep: "Skip to step",
  saveChanges: "Save changes",
  useDemoData: "Use demo data",
  signIn: "Open workbench",
  runChecks: "Run checks",
  addDocument: "Add document",
  remove: "Remove",
};

export const home = {
  recent: "Recent cases",
  noCases: "No cases yet. Start a case, or try a sample to see how it works.",
  colCase: "Case",
  colStep: "Step",
  colUpdated: "Last updated",
  icons: [
    { key: "ask", label: "Ask" },
    { key: "gather", label: "Gather and check" },
    { key: "decide", label: "Decide" },
  ],
  chooseSample: "Choose a sample",
  confirmDelete: "Delete this case? You can't undo this. Download its JSON first if you want to keep a copy.",
  importHint: "Choose a JSON file you downloaded from this tool.",
  newCaseTitle: "New case",
};

export const step1 = {
  client: "Client",
  clientHint: "The client's name. We never send it outside the firm.",
  country: "Country",
  industry: "Industry",
  fn: "Function",
  fnHint: "For example strategy, operations or marketing.",
  ask: "What does the client want to find out?",
  askHint: "Paste it exactly as they wrote it. We keep their wording as it is.",
  askShort: "the ask",
  files: "Files the client already sent",
  filesHint: "Drop files here, or choose them. csv, xlsx, txt or pdf, up to 20 MB each.",
  filesDisclosure: "Client files are read by an AI service under the account's terms.",
  neverSend: "Never send these",
  neverSendHint: "Private numbers, deals or names that must never leave the firm. One per line.",
  aliases: "Other names for the client",
  aliasesHint: "Short names or brand names. One per line. These are never sent out either.",
  aiReads: "AI reads client files",
  aiReadsHint: "When this is off, you type the key figures from each file yourself.",
  on: "On",
  off: "Off",
  typedFigures: "Figures you typed in",
  figValue: "Value",
  figUnit: "Unit",
  figWhere: "Where in the file",
  status: {
    missing: (fields: string[]) => `Fill in ${fields.join(", ")}`,
    reading: "Reading your files and the ask.",
    ready: "Ready to check",
  },
};

export const step2 = {
  belief: "What they believe",
  beliefHint: "We test this. We don't treat it as a fact.",
  decision: "The decision they face",
  measure: "How we'll compare numbers",
  measureName: "Measure",
  measureDef: "Exact definition",
  measureHint: "Used for market-size numbers, so every source counts the same thing.",
  fromFiles: "What we read from their files",
  noFiles: "No client files were added.",
  figuresFound: (n: number) => `${n} figures found`,
  notFound: "Not found in the file",
  status: { drafting: "Drafting the question.", edit: "Fill in all three boxes", ready: "Ready to confirm" },
};

export const step3 = {
  colIdea: "Idea",
  colType: "Type",
  colMeasure: "Measure",
  colTarget: "Target",
  colCritical: "Critical",
  colSource: "Target from",
  typeMarket: "Market",
  typeClient: "Client data",
  sources: { client_goal: "Client goal", benchmark: "Benchmark", estimate: "Estimate" } as Record<string, string>,
  atLeast: "at least",
  atMost: "at most",
  ideaText: "Idea",
  measureName: "Measure",
  unit: "Unit",
  direction: "Direction",
  target: "Target",
  sourceType: "Where the target comes from",
  sourceNote: "How the target was set",
  benchmarkSource: "Benchmark source",
  noBenchmark: "No benchmark source was found for this target.",
  quality: "Source quality",
  date: "Date",
  removeReason: "Why remove this idea?",
  removeReasonHint: "A short reason, kept in History.",
  removed: (reason: string) => `Removed: ${reason}`,
  formula: "Target formula",
  assumptions: "Assumptions",
  margin: "Close-call margin",
  marginHint: "Evidence this close to the target counts as a close call.",
  howDecided: "How the answer is decided",
  qualityCheck: "The quality check",
  qualityCheckHint: "Evidence that passes every test is approved without you. You still see its source.",
  searches: "Benchmark searches we ran",
  tick: "I've checked the targets and the critical ideas",
  confirmLock: "After you lock the targets, you can't edit them.",
  status: { drafting: "Drafting the ideas and fetching benchmarks.", tick: "Tick the box to lock", locked: "Targets locked" },
  rules: {
    minSources: (market: number, client: number) =>
      `Market figures need ${market} separate sources. Client data needs ${client}.`,
    recency: (a: number, b: number) =>
      `Sources must be dated within ${a} months for size, growth and price figures, or ${b} months for timing figures.`,
    spot: (pct: number, min: number) =>
      `We pick ${min} ${min === 1 ? "item" : "items"} that passed for an optional quick double-check${pct ? ` (or ${pct}% if that's more)` : ""}.`,
    trips: (free: number, max: number) =>
      `You can go back to the client ${free} times per idea. A third time needs a reason. ${max} is the limit.`,
  },
};

export const step4 = {
  tabAnswers: "Answers",
  tabSources: "Sources",
  tabRequests: "Requests",
  routes: { desk: "Desk research", client: "Client request", expert: "Expert question" } as Record<string, string>,
  coverage: {
    answered_by_client_file: "Answered by a client file",
    partly: "Partly answered",
    not_covered: "Not covered yet",
  } as Record<string, string>,
  missing: "Still missing",
  need: "What we need",
  have: "What we have",
  where: "Where",
  sourceUse: "Use",
  sourceName: "Source",
  sourceQuality: "Quality",
  sourceKinds: {
    open_web: "Web search",
    firm_archive: "Firm archive",
    paid_db: "Research database",
  } as Record<string, string>,
  eachRated: "Each result is rated by its own website",
  notUsed: (reason: string) => `Not used: ${reason}`,
  untickReason: "Why not use this source?",
  newSource: "Add a source",
  newSourceName: "Source name",
  newSourceDomain: "Website",
  newSourceQuality: "Quality",
  newSourceReason: "Why this quality?",
  clientRequest: "Request to the client",
  clientRequestNote: (gaps: number, have: number) =>
    `It lists the ${have} things we already have and asks only for the ${gaps} still missing.`,
  expertQuestions: "Questions for experts",
  checkedOut: "I've checked what goes out",
  original: "Original wording",
  cleaned: "Wording that goes out",
  removedTerms: "Removed",
  blocked: (terms: string) => `Blocked because it contained a private term: ${terms}`,
  searchesTitle: "Searches",
  confirmSent: "After you mark the requests as sent, they can't be changed. Collecting starts straight away.",
  status: {
    planning: "Preparing the research plan.",
    tick: "Tick \"I've checked what goes out\"",
    ready: "Ready to mark as sent",
  },
};

export const step5 = {
  groups: {
    open_web: "Web search",
    firm_archive: "Firm archive",
    paid_db: "Research databases",
    client_file: "Client files",
    expert_note: "Expert notes",
  } as Record<string, string>,
  states: {
    waiting: "Waiting",
    searching: "Searching",
    reading: "Adding",
    receiving: "Receiving",
    done: "Done",
    stopped: "Stopped",
    "not in plan": "Not in your sources",
  } as Record<string, string>,
  items: (done: number, total: number) => `${done} of ${total}`,
  elapsed: (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`,
  stillWaiting: "Still waiting for",
  nothingWaiting: "Nothing is waiting.",
  benchmarksNote: (n: number) => `${n} benchmarks for the targets were already found in step 3.`,
  fromWho: (who: string) => `from ${who}`,
  addReplyTitle: "Add a reply from the client or an expert",
  replyKind: "From",
  replyClient: "The client",
  replyExpert: "An expert",
  pasteHint: "Paste the reply here, or add a file.",
  log: "Log for each source",
  status: { running: "Collecting.", done: "Collecting finished" },
};

export const step6 = {
  collected: "Collected",
  separate: "Separate sources",
  rated: "Rated",
  merged: "Merged duplicates",
  noMerged: "No duplicates were found.",
  copies: (n: number) => `${n} ${n === 1 ? "copy" : "copies"} merged into`,
  calcs: "Calculations",
  noCalcs: "No calculations were needed.",
  ratings: "Source ratings",
  conversions: "Unit conversions",
  noConversions: "Every figure was already in its idea's unit.",
  notFoundCount: (n: number, total: number) =>
    `${n} of ${total} figures couldn't be found word for word in their source. They won't count in the tests.`,
  progress: {
    dedup_pre: "Looking for copies before reading.",
    read: "Reading each source and pulling out its figures.",
    grade: "Rating each source and tracing copies.",
    link: "Matching evidence to each idea.",
    checklist: "Running the quality check.",
  } as Record<string, string>,
  status: { running: "Checking the evidence.", done: "Evidence checked" },
};

export const step7 = {
  chipDecide: (a: number, b: number) => `Needs your call ${a} of ${b}`,
  chipSeen: (a: number, b: number) => `Seen ${a} of ${b}`,
  needsCall: (n: number) => `Needs your call (${n})`,
  passed: (n: number) => `Passed the quality check (${n})`,
  passedNone: "Nothing passed the quality check, so every item is under Needs your call.",
  needsNone: "Nothing needs your call.",
  colClaim: "Claim",
  colSource: "Source",
  colQuality: "Quality",
  colDate: "Date",
  colSeen: "Seen",
  spotTitle: "Quick double-check",
  spotOptional: "Optional",
  movedToCall: "Doesn't match, so it's under Needs your call",
  spotHint: "One source that passed the quality check. Open it and check the figure matches what it says, or skip it. It doesn't hold up the tests.",
  spotSkipped: "Nothing passed the quality check, so there's nothing to double-check.",
  spotSkippedByYou: "Skipped",
  checkedSources: "I've checked these sources",
  closedSection: (a: number, b: number, c: number) => `Target sources (${a}) · Rejected (${b}) · Waiting (${c})`,
  targetSources: "Target sources",
  rejected: "Rejected",
  waiting: "Waiting",
  why: "Why it needs your call",
  rejectReason: "Why reject it?",
  rejectReasons: ["Not reliable", "Out of date", "Measures something different", "Duplicate", "Not relevant"],
  rejectOther: "Other",
  rejectHint: "Add a few words if you like. It stays on record.",
  checks: "Checks",
  checkTest: "Check",
  checkNeeds: "Needs",
  checkFound: "Found",
  links: "Which idea it supports",
  role: "How it's used",
  roles: {
    supports_test: "Counts in the test",
    cross_check: "Sense check only",
    context: "Background only",
    sets_pass_line: "Sets a target",
  } as Record<string, string>,
  formula: "Calculation",
  formulaInputs: "Inputs",
  formulaUnitCheck: "The units don't line up as expected. Check the formula before you confirm it.",
  formulaAuto: "Calculated by the app from the two quoted figures.",
  formulaNeedsYou: "This calculation combines figures from different sources or uses an assumption, so check it and use \"Accept and confirm formula\".",
  acceptClientFormula: "Accept as client's data and confirm formula",
  formulaConfirmed: "Formula checked",
  quote: "Source text",
  pass: "Passed",
  fail: "Didn't pass",
  noQuote: "No quote",
  notVerified: "Not found word for word in the source",
  copiesOf: (ids: string) => `Copies merged into this one: ${ids}`,
  confirmRun: "After you run the tests, the links between evidence and ideas are locked.",
  status: {
    decide: (n: number) => `Decide ${n} more ${n === 1 ? "item" : "items"} first`,
    seen: (n: number) => `Look at ${n} more ${n === 1 ? "source" : "sources"} first`,
    box: "Tick \"I've checked these sources\"",
    ready: "Ready to run the tests",
  },
};

export const results = {
  labels: {
    holds: "Supported",
    fails: "Not supported",
    conflicting: "Sources disagree",
    not_enough: "Not enough evidence",
  } as Record<string, string>,
  confidence: { high: "Strong", medium: "Fair", low: "Weak" } as Record<string, string>,
  confidenceWord: (w: string) => `Confidence: ${w}`,
  target: "Target",
  critical: "Critical",
  evidence: "Evidence",
  noEvidence: "No evidence counted yet",
  fullReasoning: "Full reasoning",
  everyPiece: "Every piece of evidence and how it's used",
  counted: "Counted",
  notCounted: (why: string) => `Not counted: ${why}`,
  closeCall: "close call",
  barTarget: "target",
  status: { gaps: (n: number) => `${n} ${n === 1 ? "idea needs" : "ideas need"} more evidence`, none: "Every idea has enough evidence" },
};

export const step9 = {
  request: (n: number, free: number) => `Request ${n} of ${free}`,
  question: "Question to send",
  whatWeHave: "What we already have",
  drafting: "Drafting the question.",
  sentOn: "Marked as sent",
  reply: "The reply",
  replyHint: "Paste the reply, or add the file they sent.",
  reading: "Reading the reply.",
  newEvidence: "New evidence from the reply",
  sampleMix: "Sample-mix check",
  sampleMixPass: "The reply's sample matches the target group within the allowed difference.",
  sampleMixFail: "The reply's sample differs from the target group by more than the allowed difference. Consider this before you accept it.",
  sampleMixNa: "Marked as not needed.",
  dimension: "Group",
  inSample: "In the reply",
  inTarget: "Target group",
  thirdTick: "I want to ask a third time",
  thirdReason: "Why is a third request needed?",
  limitReached: "You've asked about this idea three times, which is the limit.",
  retested: "Tested again",
  pickIdea: "Choose an idea to add",
  noGaps: "Every idea has enough evidence. You can add a weak or disputed idea, or move on.",
  confirmSent: "After you mark the question as sent, you can't edit it.",
  status: {
    draft: "Draft a question for each gap",
    drafting: "Drafting the question.",
    send: "Send the question, then mark it as sent",
    reply: "Add the reply when it arrives",
    reading: "Reading the reply.",
    decide: (n: number) => `Decide ${n} more ${n === 1 ? "item" : "items"} first`,
    mix: "Finish the sample-mix check",
    retest: "Ready to test again",
    done: "Every gap has been followed up",
  },
};

export const step10 = {
  answer: "The answer",
  says: "What the evidence says",
  labels: {
    achievable: "Achievable",
    not_achievable: "Not achievable",
    consultant_decides: "Needs your decision",
  } as Record<string, string>,
  aiDraft: "AI draft",
  template: "Built from the results",
  rejectedTitle: "Rejected evidence and the reasons",
  noRejected: "No evidence was rejected.",
  adding: "Adding up the results and drafting the summary.",
  status: { running: "Adding it up.", ready: "Ready" },
};

export const step11 = {
  lockedUnchanged: "This is a what-if. Your plan doesn't change.",
  confirmRetarget: (v: string) => `This reopens your plan at step 3 with a target of ${v}. Results from step 8 onwards will be cleared and run again. Evidence you've reviewed is kept.`,
  targetOf: (code: string) => `${code} target`,
  locked: (v: string) => `locked at ${v}`,
  delta: (d: string) => `${d} from the locked value`,
  stillUnknown: "Still unknown",
  noUnknowns: "Nothing is listed as unknown.",
  restsOn: "What the answer rests on",
  checkedByYou: "checked by you",
  passedCheck: "passed the quality check",
  changed: "Changed",
  overallNow: "The answer would be",
  status: "Moving a slider never changes your locked plan",
};

export const step12 = {
  summaryTitle: "Summary",
  preparedOn: (d: string) => `Prepared ${d}`,
  ask: "The ask",
  results: "Results",
  colIdea: "Idea",
  colTarget: "Target",
  colResult: "Result",
  colConfidence: "Confidence",
  answer: "The answer",
  gaps: "Still unknown",
  noGaps: "Nothing is listed as unknown.",
  evidenceCounts: "Evidence",
  counts: (k: { collected: number; unique: number; auto_approved: number; decided_by_person: number }) =>
    `${k.collected} collected · ${k.unique} separate sources · ${k.auto_approved} passed the quality check, and you checked their sources · ${k.decided_by_person} decided by you`,
  conclusion: "Your conclusion",
  conclusionHint: "Write what you conclude and what you'd recommend. This is yours alone.",
  saved: (t: string) => `Saved ${t}`,
  audit: "Counts and audit detail",
  auditRows: {
    rejected: "Rejected",
    pending: "Still waiting",
    unreadable: "Couldn't be read",
    duplicates: "Duplicates merged",
    benchmarks: "Target sources",
  } as Record<string, string>,
  status: { empty: "Write your conclusion first", ready: "Ready to save", saved: "Conclusion saved" },
};

export const evidence = {
  status: {
    auto_approved: "Passed the quality check",
    approved: "Accepted by you",
    needs_decision: "Needs your call",
    client_reported: "From the client",
    belief_under_test: "Client's claim",
    cross_check: "Sense check only",
    pass_line_source: "Target source",
    rejected: "Rejected",
    pending: "Waiting",
    unreadable: "Could not read",
    pending_clean: "Not checked yet",
  } as Record<string, string>,
  duplicateOf: (id: string) => `Duplicate of ${id}`,
  quality: { 1: "Official", 2: "Trusted", 3: "Press", 4: "Unverified" } as Record<number, string>,
  yourCall: "Your call",
  origins: {
    open_web: "Web page",
    firm_archive: "Firm archive",
    paid_db: "Research database",
    client_file: "Client file",
    expert_note: "Expert note",
    benchmark: "Benchmark",
  } as Record<string, string>,
  undated: "No date",
  decidedReason: (r: string) => `Reason: ${r}`,
};

export const origin = { llm: "AI draft", rule_engine: "Calculated", consultant: "You", client: "Client", expert: "Expert", system: "App" } as Record<string, string>;

export const history = {
  title: "History",
  empty: "Nothing has happened in this case yet.",
  intro: "Everything done in this case, newest first.",
};

export const help = {
  title: "Help",
  stepsTitle: "The 12 steps",
  steps: [
    "Describe the ask: paste the client's request and add any files they sent.",
    "Confirm the question: check what they believe, the decision they face and how numbers are compared.",
    "Set the targets: agree the number that decides each idea, then lock it.",
    "Plan the research: check where each answer comes from and what goes out.",
    "Gathering evidence: we search the sources you chose.",
    "Checking the evidence: we merge duplicates and rate each source.",
    "Review the evidence: make the calls we can't, and check the sources that passed.",
    "Results: see how each idea compares with its target.",
    "Fill the gaps: ask a narrower question where evidence is thin.",
    "The answer: the results added up, with a short summary.",
    "What if: see whether different targets would change the answer.",
    "Your conclusion: write your own conclusion and download the summary.",
  ],
  glossaryTitle: "Words we use",
  glossary: [
    { term: "Target", text: "The number that decides whether an idea holds up. It's fixed before any evidence is read." },
    { term: "Critical", text: "An idea the answer depends on. If a critical idea isn't supported, the plan isn't achievable." },
    { term: "Source quality", text: "Official, Trusted, Press or Unverified. Set by fixed rules, never by the AI." },
    { term: "From the client", text: "Data the client gave us. It can support an idea, but confidence stays at Fair at most." },
    { term: "Sense check only", text: "Evidence you keep for comparison. It never counts in a test." },
    { term: "Quick double-check", text: "One item that passed the quality check, picked at random for you to check by hand if you want. You can skip it or switch it off in Settings." },
  ],
};

export const tips = {
  target: "The number that decides whether this idea holds up. You agree it before any evidence is read.",
  critical: "If a critical idea isn't supported, the plan isn't achievable. You need at least one.",
  quality: "Official, Trusted, Press or Unverified, set by fixed rules from the website or source type.",
  closeCall: "Evidence within this margin of the target, or a range that includes it, counts as a close call. Confidence is then Weak.",
  senseCheck: "Kept for comparison only. It never counts towards a result.",
  spot: "One item picked at random from those that passed. If it doesn't match its source, it moves to Needs your call.",
  separate: "Copies of the same original count once. Each separate source is a different original.",
};

export const settings = {
  title: "Settings",
  mode: "Data mode",
  modeDemo: "Demo data",
  modeLive: "Live",
  modeHint: "Demo data uses stored answers for the sample cases. Live uses the AI and search services.",
  keysMissing: "Live keys aren't set up yet, so only demo data is available.",
  fastDemo: "Fast mode",
  fastDemoHint: "Reads at most 4 sources per question, so gathering takes a minute or two.",
  largerText: "Larger text",
  largerTextHint: "Makes text bigger for projectors.",
  doubleCheck: "Double-check one auto-passed source",
  doubleCheckHint: "At step 7, shows one source that passed the quality check so you can compare it with the original. Optional.",
  aiReads: "AI reads client files",
  skip: "Skip to step",
  skipHint: "Replays this sample's recorded answers up to the chosen step. Every check still runs.",
  skipping: "Replaying the sample's answers.",
  caseSection: "This case",
  confirmReset: "Reset this case to step 1? The details and client files stay. Everything else is cleared.",
  confirmDelete: "Delete this case? You can't undo this. Download its JSON first if you want to keep a copy.",
  rulesTitle: "Rules and source ratings (read-only)",
  spendTitle: "Spending",
  spendCase: (usd: string, calls: number, max: number) => `This case: $${usd} · ${calls} of ${max} AI calls`,
  spendToday: (usd: string, cap: string) => `Today: $${usd} of $${cap}`,
  spendSearch: (used: number, max: number) => `Search credits for this case: ${used} of ${max}`,
  checksTitle: "Set-up checks",
  checksHint: "Checks the database, passcode, AI models and search key. Each red item says how to fix it.",
  checksRunning: "Running the checks. This takes a few seconds.",
  checksAllGreen: "Everything is set up.",
  checksRed: (n: number) => `${n} ${n === 1 ? "item needs" : "items need"} fixing.`,
  fix: "Fix",
  archiveTitle: "Firm archive",
  archiveHint: "Past studies the firm owns. They are searched by keyword in every live case and never leave the firm.",
  archiveEmpty: "No documents yet. Add a past study to search it in live cases.",
  archiveDocTitle: "Title",
  archiveDate: "Date of the data",
  freshAnswers: "Fresh answers",
  freshAnswersHint: "Asks the AI again instead of reusing saved answers. Costs more; use it only after changing a file or prompt.",
  on: "On",
  off: "Off",
};

export const errors = {
  generic: "Something went wrong. Try again in a moment.",
  load: "We couldn't load this case. Check your connection and try again.",
  step: "This screen couldn't be shown. Try again, or open another step from the stepper.",
  copy: "We couldn't copy the text. Select it and copy it yourself.",
  upload: "We couldn't add this file. Try again, or upload a csv, xlsx, txt or pdf file instead.",
  rejectReason: "Add a short reason first, then try again.",
  removeReason: "Add a short reason first, then try again.",
};
